config/routes.rb
Rails.application.routes.draw do
  resources :people

  get "/welcome/say_hello"=>"welcome#say"

  get "welcome"=> "welcome#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'welcome#index'

  match ':controller(/:action(/:id(.:format)))', :via=>:all

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  validates_presence_of :name
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

    before_action :set_event , :only=>[:show, :edit, :update, :destroy]

    # GET /events/index
    # GET /events
    def index
        @events = Event.page(params[:page]).per(10)
    end

    #ET /events/show
    def show
        @page_title = @event.name
    end

    # GET /events/new
    def new
        @event = Event.new
    end

    # POST /events/create
    def create
        @event = Event.new(event_pararms)

        if @event.save
            flash[:notice] = "新增成功"
            redirect_to :action => :index # http 303
        else
            render :action => :new #new.html.erb
        end
    end

    # GET /events/edit/id
    def edit
    end

    # POST /events/update/:id
    def update

        if @event.update(event_pararms)
            flash[:notice] = "編輯成功"
            redirect_to :action => :show, :id =>@event
        else
            render :action => :edit #edit.html.erb
        end
    end

    # GET /events/destroy/:id
    def destroy
        @event.destroy
        flash[:alert] = "刪除成功"
        redirect_to :action => :index
    end

    private

    def set_event
        @event = Event.find(params[:id])
    end

    def event_pararms
        params.require(:event).permit(:name, :description)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: %i[ show edit update destroy ]

  # GET /people or /people.json
  def index
    @people = Person.all
  end

  # GET /people/1 or /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to person_url(@person), notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to person_url(@person), notice: "Person was successfully updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy!

    respond_to do |format|
      format.html { redirect_to people_url, notice: "Person was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:name, :bio, :birthday)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	# GET /welcome/say_hello
	def say
		# puts "hello world"
		# views/welcome/say.heml.erb
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<% if @event.errors.any? %>
    <ul>
    <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %><li>
    <% end %>
    </ul>
<% end %>


<p>
    <%= f.label :name,"Name" %>
    <%= f.text_field :name %>
</p>

<p>
    <%= f.label :description, "Description" %>
    <%= f.text_area :description %>
</p>

app/views/events/edit.html.erb
<%= form_for @event, :url =>{ :controller => 'events', :action =>'update', :id => @event} do |f| %>

    <%= render :partial => "form", :locals => {:f => f} %>
    <%= f.submit "Update" %>

<% end %>

app/views/events/index.html.erb
<h1>Events list</h1>

<ul>
<% @events.each do |e| %>
    <li>
        <%= e.name %>

        <%= link_to "Show", :controller => "events", :action => "show", :id => e %>

        <%= link_to "Edit", :controller => "events", :action => "edit", :id => e %>

        <%= link_to "Delete", :controller => "events", :action => "destroy", :id => e %>
    </li>

<% end %>
</ul>

<%= link_to 'New Event', :controller =>'events', :action=>'new' %>

<%= paginate @events %>

app/views/events/new.html.erb
<%= form_for @event, :url =>{ :controller => 'events', :action =>'create'} do |f| %>

    <%= render :partial => "form", :locals => {:f => f} %>
    <%= f.submit "Create" %>

<% end %>

app/views/events/show.html.erb
<h2><%= @event.name %></h2>

<%= simple_format @event.description %>

<p><%= link_to 'Back to index', :controller =>'events', :action=>'index' %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title || "Demo" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p style="color: green"><%= flash[:notice] %></p>
    <p style="color: red"><%= flash[:alert] %></p>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: person) do |form| %>
  <% if person.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :bio, style: "display: block" %>
    <%= form.text_area :bio %>
  </div>

  <div>
    <%= form.label :birthday, style: "display: block" %>
    <%= form.date_field :birthday %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/people/_person.html.erb
<div id="<%= dom_id person %>">
  <p>
    <strong>Name:</strong>
    <%= person.name %>
  </p>

  <p>
    <strong>Bio:</strong>
    <%= person.bio %>
  </p>

  <p>
    <strong>Birthday:</strong>
    <%= person.birthday %>
  </p>

</div>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Show this person", @person %> |
  <%= link_to "Back to people", people_path %>
</div>

app/views/people/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>People</h1>

<div id="people">
  <% @people.each do |person| %>
    <%= render person %>
    <p>
      <%= link_to "Show this person", person %>
    </p>
  <% end %>
</div>

<%= link_to "New person", new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Back to people", people_path %>
</div>

app/views/people/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @person %>

<div>
  <%= link_to "Edit this person", edit_person_path(@person) %> |
  <%= link_to "Back to people", people_path %>

  <%= button_to "Destroy this person", @person, method: :delete %>
</div>

app/views/welcome/index.html.erb
<p>Hola! It's <%= Time.now %></p>

<p><%= link_to 'Hello!', welcome_say_hello_path %></p>

app/views/welcome/say.html.erb
<h1>Hello, world</h1>